- name: Play Name
  hosts: localhost
  vars:
    serial_number: QBSB-VLHZ-JQCN
  gather_facts: false
  tasks:
    - name: Update device name
      cisco.meraki.devices:
        state: present
        serial: "{{ serial_number }}"
        name: My Device
    - name: Update quality and retention settings
      cisco.meraki.devices_camera_quality_and_retention:
        state: present
        serial: "{{ serial_number }}"
        quality: High
        resolution: 1280x720
        motionDetectorVersion: 2
        audioRecordingEnabled: false
        motionBasedRetentionEnabled: false
        restrictedBandwidthModeEnabled: false
      ignore_errors: true
