- name: Play Name
  hosts: localhost
  gather_facts: false
  vars:
    network_id: L_828099381482770865
  tasks:
    - name: Create Identity PSK
      cisco.meraki.networks_wireless_ssids_identity_psks:
        meraki_suppress_logging: true
        state: present
        networkId: "{{ network_id }}"
        number: 1
        name: Sample Identity PSK
        passphrase: SamplePassphrase123
