- name: Play Name
  hosts: localhost
  vars:
    org_id: XXXXXXXX
  gather_facts: false
  tasks:
    - name: Get all organizations _devices
      cisco.meraki.organizations_devices_info:
        meraki_suppress_logging: true
        organizationId: "{{ org_id }}"
        total_pages: -1
      register: org_devices
    - name: Show All Devices
      ansible.builtin.debug:
        msg: "{{ org_devices }}"
