- name: Play Name
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create
      cisco.meraki.networks_appliance_vlans:
        meraki_suppress_logging: true
        state: present
        applianceIp: 192.168.1.2
        cidr: 192.168.1.0/24
        groupPolicyId: "101"
        id: "1234"
        ipv6:
          enabled: true
          prefixAssignments:
            - autonomous: false
              origin:
                interfaces:
                  - wan0
                type: internet
              staticApplianceIp6: 2001:db8:3c4d:15::1
              staticPrefix: 2001:db8:3c4d:15::/64
        mandatoryDhcp:
          enabled: true
        mask: 28
        name: My VLAN
        networkId: L_828099381482770865
        subnet: 192.168.1.0/24
        templateVlanType: same
