<!doctype html>
<html>
  <head>
  <title>Meraki Ansible Actions documentation index</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <link rel="stylesheet" media="all" href="https://theforeman.org/static/css/bootstrap.min.css"/>
  <link rel="stylesheet" media="all" href="https://theforeman.org/static/css/bootstrap-responsive.min.css"/>
  <link rel="stylesheet" media="all" href="https://theforeman.org/static/css/style.css"/>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
  </head>

  <body style="margin:0px 15px">
    <h1>Meraki Ansible Actions</h1>

    <hr />

    <div class="row plugin-manual">
